export type GigwageEnvironments = 'production' | 'sandbox';

export type Contractor = {
  /** The contractor's 1st address line */
  address1: string;

  /** The contractor's 2nd address line */
  address2: string;

  /** The contractor's birthdate */
  birthdate: number;

  /** The contractor's city */
  city: string;

  /** When the contractor record was created */
  created_at: number;

  /** The contractor's email address */
  email: string;

  /** Error messages generated by system */
  errors: string[];

  /** Optional customer-supplied unique identifier for this contractor */
  external_id: string;

  /** The contractor's first name */
  first_name: string;

  /** The contractor has connected an ACH account for receiving payments */
  has_ach: boolean;

  /** The contractor has a debit card for receiving payments */
  has_debit: boolean;

  /** The contractor's unique identifier */
  id: number;

  /** When the contractor accepted the invitation */
  invitation_accepted_at: number;

  /** When the contractor was sent an invitation to onboard */
  invited_at: number;

  /** The contractor's last name */
  last_name: string;

  /** The contractor's phone number */
  phone_number: string;

  /** The contractor's social security number */
  social_security: string;

  /** The contractor's state */
  state: string;

  /** The contractor's zip code */
  zip: string;
};
